pipeline:
  docker-build-push:
    image: plugins/docker
    repo: sheriff/api-proxy
    tags: 1.0.${DRONE_BUILD_NUMBER}
    secrets: [ docker_email, docker_password ]
    when:
        branch: master
        event: push

  docker-build-push-prod:
    image: plugins/docker
    repo: sheriff/api-proxy
    tags:
        - latest
        - 1.0.${DRONE_BUILD_NUMBER}
    secrets: [ docker_email, docker_password ]
    when:
          branch: refs/tags/*
          event: tag

  stage-deploy:
      image: vallard/drone-kube
      template: deployment.yaml
      namespace: stage
      when:
          branch: master
          event: push

  prod-deploy:
      image: vallard/drone-kube
      template: deployment.yaml
      when:
          branch: refs/tags/*
          event: tag
